### ISSUE TITLE
Unconditionally disable autojumping (even for unique matches)

### ISSUE THREAD

**Issue by sabah1994** [ggandor/leap.nvim#107]
Hi, as the title says, I have disabled auto jumping by "require("leap").opts.safe_labels = {}" but it still jumps when there is only one instance of searched text.

**Comment by ggandor** [comment]
Why is that a problem if there's only one instance?

**Comment by sabah1994** [comment]
For the sake of consistency, when I'm pressing the target chars and label doesn't show it kinda breaks me out of my focus. Sorry to be a pain.

**Comment by ggandor** [comment]
What about setting `highlight_unlabeled_phase_one_targets = true`? (Maybe you can set some more visible highlighting for `LeapMatch` too.) Then the target is always marked in some way.

**Comment by sabah1994** [comment]
I tried it but not my cup of tea and don't worry if it's too much work

**Comment by lars-vc** [comment]
I would like to add interest to this feature, it confuses me when I get an autojump

**Comment by atusy** [comment]
Autojump is useful when users have a specific position to leap in their mind.

I think this is true with leap's **original** behavior.

However, it is sometimes not.

I have recently developed [leap-search.nvim](https://github.com/atusy/leap-search.nvim).
With this plugin, users can leap around search matches found by `/`.
In this case, users are not always sure where to jump.

BTW, leap-search.nvim experimentally implements ugly hack to disable autojump by duplicating targets when there is only one available.

https://github.com/atusy/leap-search.nvim/blob/e99534c7f68d9dab68fb4452336bf11078db7846/lua/leap-search/init.lua#L52-L56

I think this can be done with autocmd triggered by `LeapEnter`, but not always.
leap accepts function as a `targets` option.
In this case, `LeapEnter` is too early to know if length of **actual** targets is 1 or not.

Although this might be offtopic, I also want an event something like `LeapTargeted`.

**Comment by jayeheffernan** [comment]
I'd like this as a configuration option too. Adding my thoughts below. Thanks for the great work so far though! It's very handy and well thought out.

I prefer to expect/rely on 4 keystrokes every time - rather than sometimes 3, sometimes 4. If I see a label, e.g. "t", I know that I can immediately edit once I've hit that label, so I'll just type e.g. "tciw" in one smooth motion. If I don't see a label then I'm left wondering what happened, and then a moment of realisation "oh, I'm already here... what was I doing again?". For this reason I don't want to autojump to a first match, so I've set `safe_labels = {}`, but still it jumps for a unique match. Of course I will be jumping there, but I'd prefer to type that one label myself to get that confirmation, keep the process the exact same, and wear in that mental groove. I know in theory it's easy to see that a jump occurred - the cursor moves, and you know it's going to anyway because the search group wasn't labelled (although note that this relies on the user not having a typo in their second search char - whereas a label would _show_ the user that they _did_ type it correctly). So it seems autojumping helps with the project's Auxiliary Principle of "Optimize for the common case, not the pathological", but maybe there's a trade-off with the The Ideal of low cognitive load.

Also, re the "common case": jumping to a first match might be common, but I find unique matches are not (normally I'm jumping to a variable or function name, so it's likely to appear many times near one place); so to have autojump for only one rare scenario (if `safe_labels = {}`) becomes quite surprising.

**Comment by ggandor** [comment]
I'm a bit reluctant to add this as an actual flag to the API, if only it could be handled as an edge case of other settings somehow... (like `safe_labels = {}` means "no autojump")

**Comment by ggandor** [comment]
I think I suddenly grasped the difference between the mental models of people who appreciate Sneak's model, and those who want bidirectional jump, no autojump, etc (the "EasyMotion" paradigm).

To me it feels very intuitive that traversing a short distance should require less physical effort than a great distance. I find it weird having to type a label for something that is only 2 words away. Autojump enhances this nice incrementality.

I realized that I've even had a subconscious physical metaphor for Leap's "smart" autojump all along: the targets concentrate into a more and more dense mass, which is harder to approach or cut through (or induces a stronger and stronger repulsive force... something like that).

That is, Leapers are indeed "launching" a tiny object to fly across the window, while the Hop-mindset imagines a station in space, from where you can point to destinations with a beam (or shoot landing capsules, whatever).

**Comment by jayeheffernan** [comment]
@ggandor thansk for the consideration.

> I'm a bit reluctant to add this as an actual flag to the API, if only it could be handled implicitly, as an edge case of other settings somehow... (like `safe_labels = {}` means "no autojump")

`safe_labels = {}` means "no autojump" - sounds good to me! The reason people to tend to set `safe_labels = {}` is because they don't want autojump. For those people, autojump in one niche situation, which depends on what text they have on-screen at the time, becomes particularly confusing.

As for the mental model, I can lay out some of my own experience and biases around that. When it comes to small jumps, I'm happy to use `w`, `W`, or more-rarely `f` (I don't use any plugin mapping for this, just built-in `f`), `$`, etc. I'm not "all-in" on the leap/easymotion-style motions. After using Vim for a long time, I'm pretty comfortable with the built-in motions when they're applicable.  Maybe it makes sense to reach for leap more often, but

I relate to vim-sneak's tagline though - "The missing motion for Vim". Some kinds of jumps (normally further away from the cursor) seem much more intuitive to do with the mouse. Sticking to the keyboard, leap makes for a lot less thinking than the usual "exciting puzzle" as you put it, and often works out to even less keystrokes than the optimal sequence of built-in motions. This is _the_ use-case of a plugin like leap in my workflow: not to replace small hops that can be done with `w` or `f`, not to replace _anything_ that's built-in really, but to fulfil that "missing motion" of navigating to any "random" location on-screen quickly and with minimal thought.

So yes, I am the space-station and my eyes are the beam 😂 and I don't want to care about where my cursor is or how far I'm jumping. Ordering label-chars so that jumps closer to my cursor are easier to type is a nice optimisation (and requires zero thought on my part), and I can deal with separate forward and back mappings, but otherwise I don't want to be aware of the context of what my query is, how many matches are on-screen, and where my cursor is in relation to those matches. For that to affect the number of keystrokes seems to make me think too much

**Comment by ggandor** [comment]
Yes, this makes perfect sense, if safe_labels is set to empty, that can only mean the user don't want to autojump (I cannot think of an exception), and then it shouldn't make a difference whether there are 1 or 2 (or more) targets.

> As for the mental model...

This is interesting, thanks for collecting your thoughts. 

> not to replace small hops that can be done with w or f, not to replace anything that's built-in really, but to fulfil that "missing motion" of navigating to any "random" location on-screen quickly and with minimal thought.

This is exactly how I think about it too, but with a caveat. In my mind, Leap's use case is every situation where one would otherwise _compose_ native motions, or use more than, say, 5 repeats of `w` or `b` ("2 words" was a bit extreme example). From this viewpoint, I consider even very trivial chains like `jf{X};;` "random" locations. It doesn't matter how automatical they are for us experienced Vimmers, `s{X}{Y}` is still another level of intuitiveness (and especially that autojump version, without labels).

> I don't want to be aware of the context of what my query is, how many matches are on-screen, and where my cursor is in relation to those matches. For that to affect the number of keystrokes seems to make me think too much

Autojump or not, you don't have to think about the context and _how_ it affects the keystrokes, that's the very idea; just follow the beacons (or register the lack of it), that is, sit back and type what you see, since you know the next step ahead of time (not entirely true but let's say we're halfway there). And there can be secondary label groups, so it can never be consistently 4 keystrokes anyway. But I see what you mean.

**Comment by ggandor** [comment]
Everyone: note that you can still use `s{char}<enter>` if you are sure that the target is unique, and just want to jump there right away!
