### ISSUE TITLE
Is it possible to highlight 2 chars of phase2 text too?

### ISSUE THREAD

**Issue by alexveden** [ggandor/leap.nvim#120]
Is it possible to highlight first two letters of the phase 2 matches:
![image](https://user-images.githubusercontent.com/18488560/224382185-0d1b69c8-9ce2-4552-947c-1deb3f2a830d.png)

It would be great to have a separate highlighting style of 1st letter maybe?

**Comment by ggandor** [comment]
> Is it possible to highlight first two letters of the phase 2 matches:

The point of `LeapMatch` is to differentiate between targets for which you don't need a 3rd keypress, and targets for which you do (labeled). Otherwise, without conveying this information (if all matches are highlighted), what's the point of highlighting the matches themselves?

> It would be great to have a separate highlighting style of 1st letter maybe?

Definitely not, but I think you might want to check #65, we've discussed the same request there. I'm closing this issue, feel free to continue there.
