### ISSUE TITLE
Adding dedicated f/t motions, or a section on how to set up a keymap that behaves like s{char}<enter> ?

### ISSUE THREAD

**Issue by marcusbuffett** [ggandor/leap.nvim#14]
I find myself doing s{char}<enter> a lot, when traversing on a line. Is there a way to map f{char} to do the same thing? so like f{char} then you're in traversal mode for that char.

Thank you for this awesome plugin, it's made my navigation so much faster.

**Comment by ggandor** [comment]
Hi, thanks! I'm not sure I understand the request here - in what way would it behave differently than `s{char}<enter><enter>...`?

**Comment by ggandor** [comment]
If all you want is a shortcut key for `s{char}<enter>`, you can define it like this:
```lua
function leap_f ()
  local c = vim.fn.getcharstr()
  local seq = vim.api.nvim_replace_termcodes('<plug>(leap-forward)' .. c .. '<enter>', true, true, true)
  vim.api.nvim_feedkeys(seq, '', false)
end
```
You can define a similar function for `F` with `<plug>(leap-backward)` in the sequence.

But I don't really see the purpose, isn't it simpler to just use the native `f` then, or clever-f/Sneak/Lightspeed if you want multiline f/t?

**Comment by FollieHiyuki** [comment]
I think what is being asked here is how to setup `leap.nvim` to only highlight and jump on characters within the current line.

**Comment by ggandor** [comment]
@marcusbuffett :)

**Comment by FollieHiyuki** [comment]
Hi @ggandor!

I see that the issue was closed so it would be nice if there is an example (maybe in the README) showing how this custom behavior can be set up.

Say, if I press `f` (bound to a custom leap function) then `a`, every character in the current line on the right of the cursor will be washed out, and `a` characters will be highlighted for jumping. Same goes for `F` (every characters on the left will be washed out).

**Comment by ggandor** [comment]
@FollieHiyuki That is not possible at the moment. I'm still undecided about adding a dedicated 1-character mode to the core. In the meantime, check out [flit.nvim](https://github.com/ggandor/flit.nvim).
