### ISSUE TITLE
Defaults: change `tab` to `backspace` for revert keys (`prev_target`, `prev_group`)

### ISSUE THREAD

**Issue by ggandor** [ggandor/leap.nvim#165]
`tab` is comfortable to press, and (in theory) works especially well together with right-hand keys, like `enter` (not sure, but the majority might use the right thumb for `space` too by default). The problem is that it so strongly evokes some kind of "forward" action/motion that I occasionally still hesitate before using it. 

(Feel free to leave a thumbs up/down if you have nothing more to add, but agree/disagree with the idea.)

**Comment by IndianBoy42** [comment]
How about `[,]`? It has the meaning of backward and forward in vim, its about as comfortable to press as tab and enter (can you confirm? i've actually forgotten since i've used weird layout keyboards for so long). Its nicely symmetric. And it should be safe since its generally a movement command so wouldn't be needed after a leap.

**Comment by ggandor** [comment]
The problem is these should be keys you wouldn't want to search for. As a prev/revert key both ideas are fine, but `next_target` should be something like `enter`/`tab`/etc. See also the most recent commit, I just hardcoded the current defaults, i.e. the assumption that the system only works well if it the three are mapped to the same key https://github.com/ggandor/leap.nvim/commit/3cc0e6a0b99dc18d4e5a88baa3cbe3c7b8b34566.

**Comment by teocns** [comment]
Tab can be somewhat confusing to people like me that are accustomed to TAB as a pane navigation keystroke
