### ISSUE TITLE
Edge cases (for sake of completeness)

### ISSUE THREAD

**Issue by mizlan** [ggandor/leap.nvim#36]
Hi! I am looking into leap.nvim for inspiration for internals and interface for one of my own plugins! (if I complete it, attribution will be given where it's due :])

I am asking how do you resolve these two cases, and prevent odd/unexpected behavior at the least:

### Case 1

```lua
abab
| <- cursor
```

Type `S` and then `ab` and try to access first `ab`. It doesn't seem like it has a label, despite the README saying:

> If a directly reachable match covers a label, the match will get a highlight (like in traversal mode), and the label will only be displayed after the second input, that resolves the ambiguity. If a label gets positioned over another label (this might occur before EOL or the window edge, when the labels need to be shifted left), an "empty" label will be displayed until entering the second input.

Maybe this above one is me not configuring correctly.

### Case 2

```
+-------(window)-------+
|   | <- cursor        |
|                  hihi|
|                      |
+----------------------+
```

Type 's' and then `hi` and try to access second `hi`. For me, the label seems to exist, but it is offscreen—I must zoom out in my terminal emulator (i.e., press Cmd-minus) to see it.

**Comment by ggandor** [comment]
I start with case 2, because that is simpler: if the label is offscreen, that is a bug (I cannot reproduce though). You should see `hi[label1][label2]<edge>`, or `hih[label]<edge>` (if the first one is the first `hi` match, and therefore not labeled) over `hihi<edge>`.

I guess case 1 is that weird edge case when the cursor autojumps to a position of a label, and covers it. I couldn't solve this yet in a satisfying way. Disabling the cursor highlight would be just as, if not more confusing.

**Comment by ggandor** [comment]
It just occurred to me that a plugin like your iswap.nvim is the exact use case for Leap's multiselect mode. The very concept is that instead of having to reinvent the wheel each time, Leap could be the underlying engine for all such plugins, providing a UI for the selection of targets. I don't know what exactly you're working on, but wouldn't it worth considering such a synergic approach? (Or is it an actual motion plugin? Then I'm even more curious, what new ideas you have in mind...)

**Comment by mizlan** [comment]
Thanks for your response, would you like me to file a bug report for the second case?

Also, I'm not sure my plugin, which isn't published yet, is a good fit for the leap engine, since it's a motion that doesn't use any form of search. You may see it on reddit in the coming week if i'm lucky.

**Comment by ggandor** [comment]
> would you like me to file a bug report for the second case?

Sure, thanks.

> I'm not sure my plugin, which isn't published yet, is a good fit for the leap engine, since it's a motion that doesn't use any form of search

You can feed Leap `targets` you already have, https://github.com/ggandor/leap-ast.nvim is a small example of that. If you'd rather not require a dependency, or see some limitation in the current UI for your specific use case, that's totally understandable though.

> You may see it on reddit in the coming week if i'm lucky.

I'm very excited! :)

**Comment by mizlan** [comment]
I'm a bit confused about the visible-editor-area bit:

if I have
```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                             ┃
┃   | <- cursor                               ┃
┃                                             ┃
┃                                             ┃
┃   hi hi hi hi hi hi hi hi hi hi hi hi hi hi hi hi hi hi hi zz
┃                                             ┃
┃   zz                                        ┃
┃                                             ┃
┃        zz                                   ┃
┃                                             ┃
┃                                             ┃
┃                                             ┃
┃                                             ┃
┃                                             ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
```
And I search for `zz`, I get scrolled horizontally way-off. Is this intentional?

**Comment by ggandor** [comment]
No, that is a bug (and I can reproduce). What's interesting is that lightspeed works fine.
