### ISSUE TITLE
Add flag for auto-jump to first occurrence

### ISSUE THREAD

**Issue by brettmitchelldev** [ggandor/leap.nvim#37]
I use a large scroll offset to keep my cursor vertically centered. As a side effect of this, and because leap moves the cursor to the first match automatically, my visual lock on my jump target gets broken on the second character I enter after `s`, which re-introduces that Hop/Easymotion mental pause that leap would otherwise solve for me.

Is there any way that a new config parameter could be added to turn that initial jump off?

**Comment by ggandor** [comment]
> Is there any way that a new config parameter could be added to turn that initial jump off?

We're doing something better: by adding/removing elements to/from `labels` and `safe_labels`, you can fine-tune the autojump behaviour. If you want to disable it completely, simply set `safe_labels = {}`.

That said, your problem is the unwanted scrolling before exiting the plugin, not auto-jumping itself. So simply set an autocommands to set scrolloff to 0, and restore it when exiting from Leap:

```lua
vim.api.nvim_create_autocmd('User', { pattern = 'LeapEnter',
  callback = function () 
    vim.g.saved_scrolloff = vim.o.scrolloff 
    vim.o.scrolloff = 0
 end })

vim.api.nvim_create_autocmd('User', { pattern = 'LeapLeave',
  callback = function () vim.o.scrolloff = vim.g.saved_scrolloff end
})
```

**Comment by brettmitchelldev** [comment]
Oh, that's much better than what I had in mind! Thanks for the suggestion!
