### ISSUE TITLE
Leap doesn't register commands nor keymaps

### ISSUE THREAD

**Issue by AmitGolden** [ggandor/leap.nvim#42]
Hi,
Really liked this plugin so I tried installing it with `use("ggandor/leap.nvim")`, then did a `require("leap").set_default_keymaps()`.
But then I restarted neovim and tried typing `s`, which did the default action and not leap.

Then I tried executing `:<Plug>(leap-forward)`, and got an error.

Could this be fixed?

**Comment by ggandor** [comment]
Hi! I'm awfully sorry if I'm saying something very trivial, but I don't know how experienced you are with (Neo)Vim, and I have no other idea: `require('leap').set_default_keymaps()` should be in your `init.lua` (by default, `~/.config/nvim/init.lua` on Linux, and `~/AppData/Local/nvim/init.lua` on Windows), or in some other file on the runtime path, so that it runs every time you start Neovim.

> Then I tried executing `:<Plug>(leap-forward)`, and got an error.

Yeah, it is a bit trickier than that - usually we don't want to execute `<Plug>` mappings directly, because that is not their purpose, but if we do, then we need to use `execute "normal \<Plug>(something)` (see https://stackoverflow.com/questions/18546533/execute-plug-commands-in-vim).

**Comment by AmitGolden** [comment]
Thanks for helping!
I created a separate file for setting up leap, which I required in my init.lua.

I'll try maybe doing the setup right in init.lua
If that won't work I'll maybe try setting the keybind myself using your method

**Comment by AmitGolden** [comment]
Update:
Mapping `s` to `<Plug>(leap-forward)` directly works, but dot-repeat doesn't (I've installed `vim-repeat`).
Doing `require('leap').set_default_keymaps()` right inside `init.lua` doesn't do anything.

What should I do?

**Comment by ggandor** [comment]
Do you have something else mapped to `s`, maybe? Check it with `:nmap s`. Or try `require'leap'.set_default_keymaps(true)`, that will force overwriting any other custom mappings.

**Comment by AmitGolden** [comment]
Thanks! I found out it was `nvim-cutlass` messing with `s`.
