### ISSUE TITLE
Take in 3+ characters instead of the default 2

### ISSUE THREAD

**Issue by kovasap** [ggandor/leap.nvim#43]
Is there a way to configure this plugin to take in 3 or more characters after `s`?  I often find that my files have many matches for two characters, and it's smoother for me to directly read the text at the place I want to go, as opposed to the arbitrary hint letters placed at each match by leap.  The leap-added letters require me to (1) read the place I want to go, (2) type `s{c1}{c2}`, (3) read the place again to react to the leap-added character, (4) type the character.  It seems smoother to instead (1) read the place I want to go, (2) type the characters there until my cursor gets there.  The hint letters are still useful as an escape hatch in case the string i'm searching for is long and occurs many times in the file.

I realize I'm basically just describing search, but that involves extra keystrokes to exit the search, and doesn't have hint letters.

I'm still newish to this plugin, so maybe there is another option that reduces this friction (or i just need to get used to it).

**Comment by ggandor** [comment]
The very point of Leap (and Lightspeed) is that you don't have to pause and check the "result" of your actual input ("Am I already there? Should I type more characters?"), because at every stage it's already determined what your next keypress should be. You always have to type two characters, and if there is a need for a 3rd one, you already know it after the _first_ input (well, if you're not typing extremely fast).

> require me to (1) read the place I want to go, (2) type s{c1}{c2}, (3) read the place again to react to the leap-added character

No, it's more like: (2) type `s{c1}` (3) _while_ typing `{c2}`, your brain is already processing `{label}`, if there is one (4) type `{label}`, and you're there.

With the method you described ("native search on steroids"), you also have to "react" to something - whether you arrived or not, and it worse, because you can _never_ know it beforehand. Adding hint letters complicate the thing even more, since you have to accept the pattern first (with e.g. `enter`), so that the hints can be assigned to the matches - another decision, another additional keypress. 

Pounce has an alternative solution to this: it uses fuzzy matching, and continuously _relabels_ the matches _as_ you type (it is even possible that a label disappears). Yes, that is - IMO - as confusing and un-ergonomic as it sounds. Additionally, the hints should all be uppercase characters (so that there's no need for accepting the pattern with `enter` first).

That said, you can also try Hop (there is a motion called `HopPattern`, which is basically what you requested), if not convinced, and see how that works for you.

**Comment by Alex-vZyl** [comment]
This issue actually made me understand why this plugin does what it does.  It is a really cool idea and I agree with what @ggandor says.
