### ISSUE TITLE
Edge case: jumping to character at the end of a line (before a <cr>)

### ISSUE THREAD

**Issue by TheLeoP** [ggandor/leap.nvim#51]
Edit: I just installe the plugin a couple of minutes ago and I was playing with the motions and options while reading the README. Right now I have just read the section [Jumping to the last character on a line](https://github.com/ggandor/leap.nvim#jumping-to-the-last-character-on-a-line). Should I close this? 

Using the default keymaps and given the following file:

![image](https://user-images.githubusercontent.com/53507599/191635089-1806e71d-28ac-49eb-81f4-b40521ffe16e.png)

Pressing `sa` works more or less as expected. The UI is bit misleading, thought, since it is showing the labels next to the `a`'s (because `<cr>` denotes the end of a line I guess).

![image](https://user-images.githubusercontent.com/53507599/191635337-700aa297-7548-4db5-9d53-cedf3a796fdd.png)

Then, pressing `<cr>` messes up all of the labels and it's imposible to any of the other results by using the labels displayed before pressing `<cr>`.

![image](https://user-images.githubusercontent.com/53507599/191635437-92042191-933d-434c-b8fc-6fb3df95115e.png)

**Comment by ggandor** [comment]
> Edit: I just installe the plugin a couple of minutes ago and I was playing with the motions and options while reading the README. Right now I have just read the section [Jumping to the last character on a line](https://github.com/ggandor/leap.nvim#jumping-to-the-last-character-on-a-line). Should I close this?

Yes, exactly. `<cr>` means "jump to the next match" by default. General advice: the issue tracker is not a chat room, next time (in any repo on GitHub) please at least read the docs first, instead of raising an issue after fooling around for "a couple of minutes". (A mild excuse could have been being a former Lightspeed user - `<cr>` indeed represents `\n` there.) That said, thanks for trying out the plugin, and have fun with Leap!
