### ISSUE TITLE
Feature Request: predictable labels

### ISSUE THREAD

**Issue by nat-418** [ggandor/leap.nvim#74]
Leap is great. I think it is very well designed and use it daily. I would like to recommend that the defaults labels change to become `1, 2, 3, 4, 5, 6, 7, 8, 9, 0`. Here are a few reasons why:

1. Accessibility: not everyone is a touch typist. The number row is easier to navigate.
2. Internationalization: what is ergonomic on one keyboard layout is not necessarily on another. Alpha keys are especially prone to moving around. The number row is more consistent across keyboards.
3. Programmability: scripting movement like `leap to the 3rd occurence of xy` is easier when you don't have to remember the default label order and count. Just count like any other motion.
4. Predictability: space for the next group becomes less arbitrary, it now means "move up the next ten labels".

If you don't want to change, that's fine. But I think this makes Leap more rational and useful.

**Comment by thatvegandev** [comment]
Totally valid opinion, but I disagree, and here's why:

> 1. Accessibility: not everyone is a touch typist. The number row is easier to navigate.
As a very comfortable touch typist, the number row is definitely not easier to navigate than home row (or just any) characters imo

> 3. Programmability: scripting movement like `leap to the 3rd occurence of xy` is easier when you don't have to remember the default label order and count. Just count like any other motion.
> 4. Predictability: space for the next group becomes less arbitrary, it now means "move up the next ten labels".

To me, the value of leap is that there is no need for counting. Period. You should be looking at where you want to go the whole time, so it's very different than the traditional vim motion counting paradigm.

Again, just my opinion! Hope you're able to configure it in a way that works for you!

**Comment by nat-418** [comment]
> Totally valid opinion, but I disagree, and here's why:
> 
> 
> 
> > 1. Accessibility: not everyone is a touch typist. The number row is easier to navigate.
> 
> 
> 
> As a very comfortable touch typist, the number row is definitely not easier to navigate than home row (or just any) characters imo
> 
> 
> 
> > 3. Programmability: scripting movement like `leap to the 3rd occurence of xy` is easier when you don't have to remember the default label order and count. Just count like any other motion.
> 
> > 4. Predictability: space for the next group becomes less arbitrary, it now means "move up the next ten labels".
> 
> 
> 
> To me, the value of leap is that there is no need for counting. Period. You should be looking at where you want to go the whole time, so it's very different than the traditional vim motion counting paradigm.
> 
> 
> 
> Again, just my opinion! Hope you're able to configure it in a way that works for you!
> 
> 
> 
> 
> 
> 
> 
> 

Imagine you are a touch typist on AZERTY ISO and not ANSI US layout. The defaults no longer make sense. 

What I am proposing actually gets rid of the need to count arbitrary letters in your head. You just see the number of occurences displayed for you. When doing multiselect operations like the example `paranormal` I find this especially useful. If you never do any operations requiring thinking about number of occurences then you are probably right that it adds no benefit. Maybe I am doing Leap wrong.

**Comment by GarethChetwood** [comment]
One option could be to allow the user to customise the characters that are used, similar to how Surfingkeys does with the "setCharacters" function

https://github.com/brookhong/Surfingkeys#follow-links

**Comment by nat-418** [comment]
> One option could be to allow the user to customise the characters that are used, similar to Surfingkeys and its "setCharacters" function
> 
> 
> 
> https://github.com/brookhong/Surfingkeys#follow-links

We can already do that. My proposal was about the defaults.

**Comment by ctstacey** [comment]
The believe the labels were chosen carefully so they wouldn't accidentally trigger another command (when not desired)

For example, if your cursor were at the first letter in the first line in
```
hello world
hello world
hello world
```
Pressing swo (to search forward for wo), would look like
```
hello world
hello wosld
hello wofld
```
With the cursor on w in the first row

At this point you have several options
1. accept the cursor position and start typing another vim command, for example 2x (to delete two characters)
2. type another character (one of the labels, s or f in this example) to move the cursor to one of the next matches.
3. In a larger example, you might need to press space to move to the next group of labels etc.

If the labels were numbers (as suggested by the OP), the shortcut being applied here (the ability to take option 1) would not be possible since it would start another vim command.

**Comment by ggandor** [comment]
> Accessibility: not everyone is a touch typist. The number row is easier to navigate.

Well, Vim is optimized for touch typing, learning it essential if you want to enjoy the benefits, it's part of the deal, so to say. (Categorizing this as an "accessibility" issue is a bit misleading, since nothing prevents anyone who is otherwise able to use a computer keyboard from learning touch typing moderately well in a few weeks or so.)

> Internationalization: what is ergonomic on one keyboard layout is not necessarily on another. Alpha keys are especially prone to moving around. The number row is more consistent across keyboards.

If we make the default arrangement uniformly uncomfortable for everyone, that doesn't solve anything. People using special keyboard layouts (significantly different from QWERTY/Z) can set `labels` as they see fit.

> What I am proposing actually gets rid of the need to count arbitrary letters in your head.
> ...
> If you never do any operations requiring thinking about number of occurences then you are probably right that it adds no benefit. Maybe I am doing Leap wrong.

The point of Leap is that you don't need to count anything, just look at the target, and type what you see. That said, you can actually use `count` before any Leap motion, if you want (e.g. `d3sab`).

**Comment by nat-418** [comment]
Thanks for making Leap and explaining your rationale, it was very clarifying.
