### ISSUE TITLE
Is there a way to set the wild char when type in pattern? 

### ISSUE THREAD

**Issue by woshichuanqilz** [ggandor/leap.nvim#89]
Sometimes when I meet the pattern "j=" "k+" "k_" which is hard to 

press the second char. So is there a way to set a wild char to match any char? 

For example I press "j*" can match any two char pattern start with j

**Comment by ggandor** [comment]
You can use `equivalence_classes` (mutual aliases), but wildcard characters like in your suggestion are impossible if you want ahead-of-time displayed labels. Think about it: when targeting `k+`, after pressing `k`, the plugin cannot know whether you will type `+` or `*` (the wildcard character), so it cannot decide which label to show (the labels are different in the two cases, since the wildcard would match a lot more targets).
